"use client";

import { useState } from "react";
import FileUploadButton from "../FileUploadButton";
import PasteButton from "../PasteButton";

export default function SummarizerPanel() {
  const [inputText, setInputText] = useState("");
  const [summary, setSummary] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [wordCount, setWordCount] = useState(0);
  const [selectedLength, setSelectedLength] = useState("medium");
  const [uploadedFileName, setUploadedFileName] = useState("");

  const handleTextChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    const text = e.target.value;
    setInputText(text);
    setWordCount(text.trim().split(/\s+/).filter(word => word.length > 0).length);
    setUploadedFileName("");
  };

  const handleFileUpload = (content: string, fileName: string) => {
    setInputText(content);
    setUploadedFileName(fileName);
    setWordCount(content.trim().split(/\s+/).filter(word => word.length > 0).length);
  };

  const handlePaste = (content: string) => {
    setInputText(content);
    setUploadedFileName("");
    setWordCount(content.trim().split(/\s+/).filter(word => word.length > 0).length);
  };

  const handleError = (error: string) => {
    alert(error);
  };

  const handleSummarize = async () => {
    if (!inputText.trim()) {
      alert("Please enter some text to summarize!");
      return;
    }

    setIsLoading(true);
    try {
      // Import the API client
      const { ApiClient } = await import("@/lib/api-client");
      
      // Get real AI-generated summary using Gemini
      const result = await ApiClient.generateSummary(
        inputText, 
        selectedLength as "short" | "medium" | "long"
      );
      
      setSummary(result.summary);
    } catch (error) {
      console.error("Error generating summary:", error);
      
      // Fallback summary if API fails
      setSummary(
        "This is a sample summary of your text. In a real application, this would be generated by an AI model based on the text you provided. The summary captures the key points and main ideas from your input."
      );
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-black p-8">
      {/* Header */}
      <div className="mb-8">
        <div className="flex items-center justify-between mb-2">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-gradient-to-br from-blue-500 to-purple-600 rounded-lg flex items-center justify-center">
              <svg className="w-6 h-6 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
            </div>
            <div>
              <h1 className="text-2xl font-bold text-white">Summarizer</h1>
              <p className="text-green-200/70 text-sm">
                Transform lengthy content into concise summaries
              </p>
            </div>
          </div>
          <button className="bg-green-500 hover:bg-blue-700 text-white px-4 py-2 rounded-lg text-sm font-medium transition-colors flex items-center gap-2">
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
            </svg>
            Summarizer
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Input Section */}
        <div className="bg-gray-950 rounded-xl border border-green-500/20 p-6">
          <div className="mb-4">
            <div className="flex items-center justify-between mb-3">
              <label className="text-white font-medium flex items-center gap-2">
                Input <span className="text-green-400 flex items-center gap-1">
                  <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                  </svg>
                  0 Words
                </span>
              </label>
              <span className="text-green-200/70 text-sm">{wordCount} words</span>
            </div>

            <textarea
              value={inputText}
              onChange={handleTextChange}
              placeholder="Paste or type your text here to generate a summary..."
              className="w-full h-64 bg-black border border-green-500/30 rounded-lg p-4 text-green-200 placeholder-green-300/50 focus:outline-none focus:border-green-500 resize-none"
            />
          </div>

          {uploadedFileName && (
            <div className="mb-4 flex items-center gap-3 bg-black border border-green-500/30 rounded-lg p-3">
              <span className="text-green-400">📄</span>
              <span className="text-green-200 text-sm flex-1">{uploadedFileName}</span>
              <button
                onClick={() => {
                  setUploadedFileName("");
                  setInputText("");
                  setWordCount(0);
                }}
                className="text-green-200/70 hover:text-red-400 transition-colors"
              >
                ✕
              </button>
            </div>
          )}

          {/* Action Buttons */}
          <div className="flex gap-3 mb-4">
            <PasteButton
              onPaste={handlePaste}
              onError={handleError}
              label="Paste Text"
            />
            <FileUploadButton
              onFileContent={handleFileUpload}
              onError={handleError}
              accept=".txt,.md,.pdf,.doc,.docx"
              label="Upload File"
            />
          </div>

          {/* Length Selection */}
          <div className="mb-4">
            <label className="text-white text-sm font-medium mb-2 block">
              Summary Length
            </label>
            <div className="flex gap-2">
              {["short", "medium", "long"].map((length) => (
                <button
                  key={length}
                  onClick={() => setSelectedLength(length)}
                  className={`flex-1 px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
                    selectedLength === length
                      ? "bg-green-500 text-white"
                      : "bg-gray-800 text-green-200/70 hover:bg-gray-700"
                  }`}
                >
                  {length.charAt(0).toUpperCase() + length.slice(1)}
                </button>
              ))}
            </div>
          </div>

          {/* Summarize Button */}
          <button
            onClick={handleSummarize}
            disabled={isLoading || !inputText.trim()}
            className="w-full bg-gradient-to-r from-green-500 to-green-600 hover:from-blue-700 hover:to-purple-700 text-white px-6 py-3 rounded-lg font-medium transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
          >
            {isLoading ? (
              <>
                <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                Summarizing...
              </>
            ) : (
              <>
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z" />
                </svg>
                Summarize (Free)
              </>
            )}
          </button>
        </div>

        {/* Output Section */}
        <div className="bg-gray-950 rounded-xl border border-green-500/20 p-6">
          <div className="mb-4">
            <div className="flex items-center justify-between mb-3">
              <label className="text-white font-medium">Summary</label>
              {summary && (
                <button className="text-green-400 hover:text-blue-300 text-sm flex items-center gap-1">
                  <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                  </svg>
                  Copy
                </button>
              )}
            </div>

            <div className="w-full h-64 bg-black border border-green-500/30 rounded-lg p-4 overflow-y-auto">
              {summary ? (
                <p className="text-green-200 leading-relaxed">{summary}</p>
              ) : (
                <div className="h-full flex flex-col items-center justify-center text-center">
                  <div className="w-16 h-16 bg-green-500/20 rounded-full flex items-center justify-center mb-4">
                    <svg className="w-8 h-8 text-green-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                    </svg>
                  </div>
                  <p className="text-green-200/70 font-medium mb-2">
                    Your summary will appear here
                  </p>
                  <p className="text-green-300/50 text-sm max-w-xs">
                    Enter your text and click "Summarize" to generate a summary.
                  </p>
                </div>
              )}
            </div>
          </div>

          {/* Summary Stats */}
          {summary && (
            <div className="bg-black rounded-lg p-4 border border-green-500/30">
              <div className="grid grid-cols-3 gap-4 text-center">
                <div>
                  <div className="text-green-200/70 text-xs mb-1">Original</div>
                  <div className="text-white font-semibold">{wordCount} words</div>
                </div>
                <div>
                  <div className="text-green-200/70 text-xs mb-1">Summary</div>
                  <div className="text-green-400 font-semibold">
                    {summary.split(/\s+/).length} words
                  </div>
                </div>
                <div>
                  <div className="text-green-200/70 text-xs mb-1">Reduction</div>
                  <div className="text-green-400 font-semibold">
                    {Math.round((1 - summary.split(/\s+/).length / wordCount) * 100)}%
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Features Info */}
      <div className="mt-8 grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="bg-gray-950 rounded-xl border border-green-500/20 p-6">
          <div className="w-12 h-12 bg-green-500/20 rounded-lg flex items-center justify-center mb-4">
            <svg className="w-7 h-7 text-green-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
            </svg>
          </div>
          <h3 className="text-white font-semibold mb-2">Lightning Fast</h3>
          <p className="text-green-200/70 text-sm">
            Get instant summaries powered by advanced AI technology
          </p>
        </div>

        <div className="bg-gray-950 rounded-xl border border-green-500/20 p-6">
          <div className="w-12 h-12 bg-green-500/20 rounded-lg flex items-center justify-center mb-4">
            <svg className="w-7 h-7 text-green-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
          </div>
          <h3 className="text-white font-semibold mb-2">Accurate Results</h3>
          <p className="text-green-200/70 text-sm">
            Capture key points and main ideas with precision
          </p>
        </div>

        <div className="bg-gray-950 rounded-xl border border-green-500/20 p-6">
          <div className="w-12 h-12 bg-green-600/20 rounded-lg flex items-center justify-center mb-4">
            <span className="text-2xl">📚</span>
          </div>
          <h3 className="text-white font-semibold mb-2">Multiple Formats</h3>
          <p className="text-green-200/70 text-sm">
            Support for text, PDFs, and various document types
          </p>
        </div>
      </div>
    </div>
  );
}
